version: '3'
volumes:
  node_modules:

services:
  app:
    image: node:8
    command: yarn start
    working_dir: '/app'
    environment:
      HOST: '0.0.0.0'
      PORT: 3000
    volumes:
      - './:/app/'
      - node_modules:/app/node_modules/
    ports:
      - '3000:3000'
      - '5858:5858'
