version: '3'

volumes:
	node_modules:

services:
	app:
    image: node:8
    command: npm start
    working_dir: '/app'
    volumes:
    	- './:/app/'
    	- node_modules:/app/node_modules/
    ports:
    	- '8000:8000'
